/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 * main.c - Auto-generated by Anjuta's Makefile project wizard
 * 
 */

#include <stdio.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>

#include  <pthread.h> 
#include "msgque.h"


static changid_x=0;

void msgque_Readthread(void* param)
{
	struct msgbuffer msg;
	key_t key;
	
	if( changid_x == 0 )
	{
		key = msgque_init("/tmp",11010,1 );
	}
	else
	{
		key = msgque_init("/tmp",11011,1 );
	}

	
	while(1)
	{

		if( msgque_rev(key, &msg) <= 0 )
		{	
			sleep(2);
			continue;
		}
		printf("recv:msgid=%d,text=[%s] \n",msg.mtype,msg.mtext );

	}
}

int main( int argc , char* argv[] )
{

	key_t key;
	struct msgbuffer msg;
	pthread_t threadid;	
	char buf[BUFFER_SIZE];

	if( argc >=2 )
	{
		changid_x = 1;
	}

	if( changid_x == 1 )
	{
		key = msgque_init("/tmp",11010,1 );
	}
	else
	{
		key = msgque_init("/tmp",11011,1 );
	}
	
	pthread_create(&threadid,NULL,(void*)msgque_Readthread,NULL);	
	while(1)
    {
        fprintf(stdout,"Send:",NULL);
        fflush(stdout);
        fgets(buf,BUFFER_SIZE,stdin);
        if(strcmp(buf,"exit\n") == 0)
        {
            break;
        }

		if( strlen(buf)> 1)
			msgque_send(key, 123, buf, strlen(buf)-1);
   }  

	msgque_del();		
	return (0);
}
